# Configuration for cargo-release

# Sign commits and tags
sign-commit = true
sign-tag = true

# Run these commands before release
pre-release-hook = ["cargo test", "cargo clippy -- -D warnings", "cargo fmt -- --check"]

# Commit message for version bump
pre-release-commit-message = "chore: release version {{version}}"

# Don't push to remote automatically
push = false

# Don't publish to crates.io automatically  
publish = false

# Tag format
tag-prefix = "v"
tag-message = "Release version {{version}}"

# Update these files with version
pre-release-replacements = [
  # Update version in title
  {file="README.md", search="# secretscan 🔍 v[0-9.]+", replace="# secretscan 🔍 v{{version}}"},
  # Update download links
  {file="README.md", search="secretscan-v[0-9.]+-x86_64", replace="secretscan-v{{version}}-x86_64"},
  # Update any other version references
  {file="README.md", search="secretscan/v[0-9.]+", replace="secretscan/v{{version}}"},
  {file="README.md", search="secretscan [0-9.]+", replace="secretscan {{version}}"},
  # Update version in main.rs if using clap
  {file="src/main.rs", search="version = \"[0-9.]+\"", replace="version = \"{{version}}\""},
  # Update CHANGELOG
  {file="CHANGELOG.md", search="## \\[Unreleased\\]", replace="## [Unreleased]\n\n## [{{version}}] - {{date}}"},
]

# Changelog generation would require git-cliff
# [[pre-release-hook]]
# command = "git"
# args = ["cliff", "-o", "CHANGELOG.md", "--tag", "v{{version}}"]